### ISSUE TITLE
Error at start and phpbb

### ISSUE THREAD

**Issue by bettinz** [JamesDooley/VersionFinder#9]
Hello, this message appear when I run version finder:
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `getent passwd HASH(0x1234567)'
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `getent passwd HASH(0x1234567)'

I've replaced the address with 1234567.
Another bug is with phpBB updated yesterday:
I've version 3.2.1 (latest) but the program say:
 - Version installed is greater than signature, either this is a beta release or the signature file is outdated.
I've run the update before, but it's curious.
Thanks

**Comment by JamesDooley** [comment]
First I would recommend running a --update, as sometimes during an automatic update, things get wonky.
There is also a update check lockout for 24 hours to ensure that it does not check for updates every time you run the script.  --update bypasses this lockout and downloads both files even if they are up to date.

If you are still seeing phpBB being newer than the signature, verify that the signature file is reading 3.2.1 by running --signatures.  I just added 3.2.1 on my test box and it does appear to work, so I suspect a manual update will fix the issue.

The hash issue is odd, if an update does not fix it we will have to try to figure out what is causing that.  The function that the message is being generated in gets a single user as a string.  The string is generated from a directory listing of files in /var/cpanel/users or can be manually applied using --user.  Was this run with --user?

**Comment by JamesDooley** [comment]
It does look like there was a bug related to the old signature file being used after an update.  I fixed this, so it should use the latest signature file after an update.

**Comment by bettinz** [comment]
Hello @JamesDooley , thanks for the update. I'll run it again tonight.
About the hash error, the update doesn't solve the problem: if I run with --user it works without problems. If I doesn't explicit an user it says hash error but after that it works as expected. I'm running CloudLinux 6.9 and cPanel 64 if it can be helpful. Can I do some tests in order to help you?

**Comment by JamesDooley** [comment]
I added a line to the getUserDir function that should dump the contents of $user if it encounters a reference.

This should now print a message and return instead of blindly passing $user to getent passwd.  Hopefully this will give us an idea as to what is causing this.

When testing please make sure you force an update with --update first.

**Comment by bettinz** [comment]
Hello, this is what I've done:
1) rm versionfinder, signature and update files
2) wget versionfinder
3) run versionfinder --update
4) run versionfinder

This is the message:
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `getent passwd HASH(0x1234567)'
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `getent passwd HASH(0x1234567)'
Checking for updates:
- Checking versionfinder.pl [Update Needed]
Attempting to update versionfinder.pl [Updated]
- Checking .vf_signatures [Update Needed]
Attempting to update .vf_signatures [Updated]
Main script updated, restarting

sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `getent passwd HASH(0x1234567)'
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `getent passwd HASH(0x1234567)'
Checking for updates: [Deferred]
Hope this help 😄

**Comment by JamesDooley** [comment]
I just added debug output for everything being passed to getUserDir.

If you can run `versionfinder --debug` you should see what is being passed for each call.
You can ctrl-c once it checks for updates and starts scanning.

**Comment by bettinz** [comment]
Ok, this is curious:

DEBUG 1: getUserDir called with: $VAR1 = 'test1';

DEBUG 1: Running: getent passwd test1
DEBUG 1: getUserDir called with: $VAR1 = 'test2';

DEBUG 1: Running: getent passwd test2

DEBUG 1: getUserDir called with: $VAR1 = 'HASH(0x1234567)';

DEBUG 1: Running: getent passwd HASH(0x1234567)
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `getent passwd HASH(0x1234567)'
DEBUG 1: getUserDir called with: $VAR1 = 'HASH(0x2234567)';

DEBUG 1: Running: getent passwd HASH(0x2234567)
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `getent passwd HASH(0x2234567)'

I've just changed hash values

**Comment by JamesDooley** [comment]
You don't happen to have a file called HASH(SOMETHING) in /var/cpanel/users do you?

Ultimately we are doing a glob of that directory and pulling the file names, so if there is a file with a weird name, it could do that.  cPanel is written in perl, so it is possible it puked a hash ref as a file name.

If not, I do have some code I can push to change how we are getting that list of accounts, but I would like to know what was happening before doing so.

**Comment by JamesDooley** [comment]
Side note on that, since perl randomizes hash memory locations, those numbers should have changed every run, unless it was an actual file name.

**Comment by bettinz** [comment]
Ok, my fault, I don't know why, but I actually have 2 files in /var/cpanel/users called 
HASH(0x1234567) and HASH(0x2234567)
If I look closer created date was april 2014 so I really don't know what it is. Sorry for waste of time caused by this thing.

**Comment by JamesDooley** [comment]
Not a problem at all, linux has a funny way of accepting almost any character as valid file names.
I have spent a lot of time working around those issues. 

I am going to close this issue, if you run in to any other issues please feel free to let me know.
